export default {
  state: () => ({
    project: {},
    data: {
      id: "",
      name: "ИТП",
      type: "",
      b_name: "",
      floor: "",
      h: null,
      region: 0,
      naspunkt: "",
    },
    isx: {
      t1: 95,
      t2: 70,
      t11: 90,
      t21: 65,
      t13: 95,
      t23: 70,
      t3: 63,
      t4: 40,
      t1_l: 70,
      t2_l: 40,
      txv_z: 5,
      txv_l: 15,
      p1: 51,
      p2: 35,
      kchn: 2.2,
      ktp: 0.25,
    },
    in: {
      data: { type: "ot_", name: "Узел ввода тепловой сети" },
      du: { dut1: null, dut2: null },
      rpd: {
        name: null,
        cod: null,
        du: null,
        kvs: null,
        kvs_r: null,
        diap: null,
        dp: 0.5,
        dp_f: null,
      },
    },
    ot: {
      data: {
        type: "ot_",
        name: "Узел отопления",
        name_sys: "Отопление",
        dp: 5,
      },
      du: { dut11: null, dut21: null },
      valve: {
        name: null,
        cod: null,
        drive: null,
        du: null,
        kvs: null,
        kvs_r: null,
        priv: null,
        dp: 0.5,
        dp_f: null,
      },
      pump: {
        name: null,
        cod: null,
        du: null,
        g: null,
        g_f: null,
        h: null,
        n: null,
        p: null,
        p_c: 2,
        p_t: 2,
        h_z: 1,
        u: null,
      },
      check_v: {
        name: null,
        cod: null,
        du: null,
        n: 1,
        d: null,
        p: null,
        h: null,
      },
      tank: {
        name: null,
        cod: null,
        q: null,
        h: null,
        v: null,
        v_f: null,
        n: null,
        k: 10,
        e: null,
        c: null,
        kef: null,
        p0: null,
        p: null,
      },
      pump_p: {
        name: null,
        cod: null,
        du: null,
        g: null,
        g_f: null,
        h: null,
        h_f: null,
        n: null,
        p: null,
      },
      to: {
        name: null,
        cod: null,
        q: null,
        num: "1x100%",
        num_pl: null,
        f: null,
        massa: null,
        h: null,
      },
    },
    vent: {
      data: { type: "vent_", name: "etrte", name_sys: "Вентиляция" },
    },
    gvs: {
      data: { type: "gvs_", name: "Узел ГВС", name_sys: "ГВС", sx: null },
      du: { dut11: null, dut21: null },
      valve: {
        name: null,
        cod: null,
        drive: null,
        du: null,
        kvs: null,
        kvs_r: null,
        priv: null,
        dp: 0.5,
        dp_f: null,
        dp_f_l: null,
      },
      pump: {
        name: null,
        cod: null,
        du: null,
        g: null,
        g_f: null,
        h: null,
        n: null,
        p: null,
        p_c: 2,
        p_t: 2,
        h_z: 1,
      },
      to1: {
        name: null,
        cod: null,
        q: null,
        num: "1x50%",
        num_pl: null,
        f: null,
        massa: null,
        h: null,
      },
      to2: {
        name: null,
        cod: null,
        q: null,
        num: "1x50%",
        num_pl: null,
        f: null,
        massa: null,
        h: null,
      },
    },
    atm: {
      tipSB: 0,
      pltr: ["gsm", "usba"],
    },
  }),

  getters: {},
  mutations: {},
  actions: {},
};
