export default {
  state: () => ({
    project: {},
    DATA: {
      id: "",
      name: "ИТП",
      type_gvs: "close",
      type: "",
      IL: false,
    },
    ot: {
      isx: {
        q: null,
        qco: null,
        qvent: null,
        t1: 95,
        t2: 70,
        p1: 50,
        p2: 40,
        t11: 95,
        t21: 70,
        sx_ot: 0,
        fuCo: 0,
        t_srez: "",
        revers: 0,
      },
      data: { type: "ot_", name: "Узел учета тепловой энергии" },
      uu: {
        di1: null,
        di2: null,
        di9: null,
        dut1: null,
        dut2: null,
        dut9: null,
        tipIm1: 6,
        tipIm9: 5,
        filter: 0,
        filter_p: 0,
        tipL: "kl",
        tipLp: "kl",
        izmL: false,
        otmetka_T1: "",
        otmetka_T2: "",
        otmetka_T9: "",
      },
    },
    gvs: {
      isx: {
        q: null,
        qs: null,
        t1: 60,
        t2: 50,
        p1: 50,
        p2: 40,
        kchn: 2.2,
        knp: 0.8,
        ktp: 0.25,
        beta: 1.3,
        txvL: 15,
        txvZ: 5,
        t1L: 70,
        t2L: 40,
        progr_txv: 0,
        txv_pr: 10,
      },
      data: { type: "gvs_", tup: "", name: "Узел учета ГВС" },
      uu: {
        di1: null,
        di2: null,
        dut1: null,
        dut2: null,
        tipIm1: 6,
        tipIm2: 6,
        filter: 0,
        tipL1: "kl",
        tipL2: "kl",
        ok: false,
        izmL: false,
        otmetka_T3: "",
        otmetka_T4: "",
      },
    },
    atm: {
      tipSB: 0,
      pltr: ["gsm", "usba"],
      lvru: 30,
      lsbo: 15,
      lsbg: 15,
      met_ruk: 0,
      teploiz_ot: "enflex13",
      teploiz_gvs: "enflex13",
      progr_txv: 0,
      txv_pr: 10,
      region: 0,
      naspunkt: "",
      listn: {
        prsx: "Принципиальная схема",
        spl: "Ситуационный план. Фрагмент плана теплового пункта",
        mont_ot: "Монтажная схема узла учета отопления",
        mont_gvs: "Монтажная схема узла учета ГВС",
        funcsx: "Функциональная схема автоматизации",
        spec: "Cпецификация оборудования, изделий и материалов",
      },
      format: {
        prsx: "",
        spl: "",
        mont_ot: "",
        mont_gvs: "",
        funcsx: "",
        spec: "",
      },
      prim: {
        prsx: "",
        spl: "",
        mont_ot: "",
        mont_gvs: "",
        funcsx: "",
        spec: "",
      },
      add: {
        prsx: "",
        spl: "",
        mont_ot: "",
        mont_gvs: "",
        funcsx: "",
        spec: "",
      },
    },
    dop: {
      truba_dop: "",
      tpl_dop: "",
      perehod_dop: "",
      otvod_dop: "",
      kozuh: 0,
    },
  }),

  getters: {},
  mutations: {},
  actions: {},
};
