export default {
  state: () => ({
    project: {},
    DATA: {
      id: "",
      name: "Узел учета ХВС",
      type: "h",
      IL: false,
    },
    hvs: {
      isx: {
        G1v: null,
        Gvsut: null,
        Tper: 24,
        t1: 5,
        p1: 50,
      },
      data: { type: "hvs_", name: "Узел учета ХВС" },
      uu: {
        di1: null,
        dut1: null,
        tipIm1: 6,
        filter: 0,
        baypass: 0,
        sens_d: true,
        sens_t: false,
        tipL: "kl",
        izmL: false,
        otmetka_B1: "",
      },
    },
    atm: {
      tipSB: 0,
      shifr_to: "",
      pltr: ["gsm", "usba"],
      lvru: 30,
      lsbh: 15,
      met_ruk: 0,
      teploiz_hvs: "",
      listn: {
        prsx: "Принципиальная схема",
        spl: "Ситуационный план. Фрагмент плана",
        mont_hvs: "Монтажная схема узла учета ХВС",
        funcsx: "Функциональная схема автоматизации",
        spec: "Cпецификация оборудования, изделий и материалов",
      },
      format: {
        prsx: "",
        spl: "",
        mont_hvs: "",
        funcsx: "",
        spec: "",
      },
      prim: {
        prsx: "",
        spl: "",
        mont_hvs: "",
        funcsx: "",
        spec: "",
      },
      add: {
        prsx: "",
        spl: "",
        mont_hvs: "",
        funcsx: "",
        spec: "",
      },
    },
    dop: {
      truba_dop: "",
      tpl_dop: "",
      perehod_dop: "",
      otvod_dop: "",
      kozuh: 0,
    },
  }),

  getters: {},
  mutations: {},
  actions: {},
};
