const opt = {
    du: [
        { text: "нет", value: 0 },
        { text: "15", value: 15 },
        { text: "20", value: 20 },
        { text: "25", value: 25 },
        { text: "32", value: 32 },
        { text: "40", value: 40 },
        { text: "50", value: 50 },
        { text: "65", value: 65 },
        { text: "80", value: 80 },
        { text: "100", value: 100 },
        { text: "125", value: 125 },
        { text: "150", value: 150 },
        { text: "200", value: 200 },
        { text: "250", value: 250 },
        { text: "300", value: 300 },
        { text: "350", value: 350 },
        { text: "400", value: 400 },
        { text: "500", value: 500 },
    ],
    du_im: [
        { text: "нет", value: 0 },
        { text: "15", value: 15 },
        { text: "25", value: 25 },
        { text: "32", value: 32 },
        { text: "40", value: 40 },
        { text: "50", value: 50 },
        { text: "65", value: 65 },
        { text: "80", value: 80 },
        { text: "100", value: 100 },
        { text: "150", value: 150 },
        { text: "200", value: 200 },
        { text: "300", value: 300 },
    ],
    sx_ts: [
        { text: "закрытая", value: "close" },
        { text: "Открытая", value: "open" },
        { text: "1 ступ теплообмен", value: "1st" },
        { text: "2 ступ теплообмен", value: "2st" },
    ],
    tip_im: [
        { text: "И6", value: 6 },
        { text: "К5", value: 5 },
    ],
    tip_lin: [
        { text: "Классическая", value: "kl" },
        { text: "Модифицированная", value: "ml" },
    ],
    tip_filtr: [
        { text: "без фильтра", value: 0 },
        { text: "сетчатый фильтр", value: 1 },
        { text: "грязевик", value: 2 },
    ],
    podp: [
        { text: "зависимая", value: 0 },
        { text: "независимая (с подпиткой)", value: 1 },
    ],
    fuco: [
        { text: "закрытая (М1 = М2)", value: 0 },
        { text: "открытая (М1 - М2)", value: 1 },
    ],
}
export default opt;